
<?php $this->layout('websitelayout::default', [
    'title' => 'Mehmet Gökce',
    ]) ?>


<div id="fh5co-about" class="animate-box">
		<div class="container">
			<div class="row">
				<div class="col-md-8 col-md-offset-2 text-center fh5co-heading">
					<h2>About Me</h2>
				</div>
			</div>
			<div class="row">
				<div class="col-md-4">
					<ul class="info">
						<li><span class="first-block">Full Name:</span><span class="second-block">Mehmet Gökce</span></li>
						<li><span class="first-block">Email:</span><span class="second-block">mg@mehmetgoekce.com</span></li>
						<li><span class="first-block">Website:</span><span class="second-block">www.mehmetgoekce.com</span></li>
					</ul>
				</div>
				<div class="col-md-8">
					<h2>Hello There!</h2>
                                        <h2>My Name is Mehmet </h2>
					<p>I'm from Augsburg, Germany</p>
                                        <p>I'm a Developer since 1998. I've worked in many kind of projects. Started with Web Development and Application Programming. I have also worked as a Network Administrator. I've developed from simple static webpages to fully managed web applications, web services or eCommerce applications. <br>
                                        I am focused on PHP and Javascript, but I've also worked with other technologies, like Java. I'm a passionate programmer. I love my job and always give my best. I'm very committed with what I do, and always try to learn new things and be active.</p>
					<p>
						<ul class="fh5co-social-icons">
							<li><a href="https://twitter.com/mehmetgoekce"><i class="icon-twitter2"></i></a></li>
							<li><a href="https://de.linkedin.com/in/mehmetgoekce"><i class="icon-linkedin2"></i></a></li>
							<li><a href="https://github.com/MehmetGoekce"><i class="icon-github2"></i></a></li>
						</ul>
					</p>
				</div>
			</div>
		</div>
	</div>

	
	